access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}

refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}

spring:
  profiles:
    active: dev
  application:
    name: project-hackaton

  datasource:
    url: jdbc:postgresql://localhost:5432/hackaton
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

  security:
    filter:
      order: 10
    oauth2:
      client:
        registration:
          google:
            client-id: your-client-id
            client-secret: your-client-secret
            redirect-uri: http://localhost:8080/login/oauth2/code/google
      resourceserver:
        jwt:
          issuer-uri: https://your-identity-provider.com

logging:
  level:
    org.springframework.security: DEBUG
