
spring:
  application:
    name: project-hackaton

  datasource:
    url: jdbc:postgresql://localhost:5432/hackaton
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

  security:
    filter:
      order: 10
    oauth2:
      client:
        registration:
          google:
            client-id: your-client-id
            client-secret: your-client-secret
            redirect-uri: http://localhost:8080/login/oauth2/code/google
      resourceserver:
        jwt:
          issuer-uri: https://your-identity-provider.com
  logging:
    level:
      org.springframework.security: trace

jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem

  expiration-time:
    access-token: 3600
    refresh-token: 1296000